
# Override specific settings here if needed
[window.position]
x = 2500
y = 700

[general]
# Alacritty Configuration
# Main configuration file that imports base settings and theme

import = [
    "~/.config/alacritty/base.toml",
    "~/.config/alacritty/github-dark.toml",
]
