[env]
term = "xterm-256color"

[font]
size = 12
offset.y = 6

[cursor]
style = "Block"

# [font.bold]
# family = "ComicShannsMono Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "ComicShannsMono Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "ComicShannsMono Nerd Font"
# style = "Italic"

# [font.normal]
# family = "ComicShannsMono Nerd Font Mono"
# style = "Regular"

# [font.normal]
# family = "ComicShannsMono Nerd Font Mono"
# style = "Regular"

# [font.normal]
# style = "Regular"

[font.normal]
#family = "CaskaydiaMono Nerd Font Mono"
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"

[scrolling]
multiplier = 15

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = false
dynamic_title = false
opacity = 0.8
startup_mode = "Windowed"
blur = true

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 20
y = 10

[window.position]
x = 2500
y = 700

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/github-dark.toml"
]
