# One Dark Theme for Alacritty
# A dark theme inspired by Atom's One Dark syntax theme

[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

[colors.cursor]
text = '#282c34'
cursor = '#abb2bf'

[colors.selection]
text = 'CellForeground'
background = '#3e4451'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

# Additional indexed colors for extended compatibility
[[colors.indexed_colors]]
index = 16
color = '#d19a66'

[[colors.indexed_colors]]
index = 17
color = '#f65866'